GLOBAL:
  USE_GPU: true
  RESUME: false
  RESUME_PATH: ./train_log/2022-0926_1009/checkpoints/best.pth
  DEVICE: '3' # 'cpu' or '0' or '0,1,2,3' ...
  EPOCH_NUM: 300
  SAVE_RESULT_DIR: ./train_log
  SAVE_EPOCH_STEP: 1
  VAL_EPOCH_STEP: 1
  PRETRAINED_MODEL: ./pretrained_model/resnet34.pth
  DISTRIBUTED: true
  EARLY_STOP_PATIENCE: 5
  TRAIN_DIR: ./data_dir/train
  VAL_DIR: ./data_dir/val
  TEST_DIR: ./data_dir/test
  VISUAL_AUGMENTATION: true
  USE_AMP: false

TRAIN:
  IMG_SIZE: 224
  TRANSFORMS_RANDOMHORIZONTALFLIP: true
  TRANSFORMS_RANDOMVERTIACALFLIP: true
  TRANSFORMS_COLORJITTER:
  TRANSFORMS_BRIGHTNESS: 0.1
  TRANSFORMS_CONTRAST: 0.1
  TRANSFORMS_SATURATION: 0.1
  TRANSFORMS_HUE: 0
  BATCHSIZE_PER_CARD: 64
  DROP_LAST: true
  NUM_WORKERS: 4

MODEL:
  NAME: resnet34

CRITERION:
  NAME: CE
  COORD_RATIO: 1
  CLASSIFIER_RATIO: 0.5

OPTIMIZER:
  NAME: SGD
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  NESTEROV: true
  LR_NAME: cosine_lr
  LR_LRF: 0.2
  LEARNING_RATE: 0.0015
  WARMUP_EPOCH: 5
